---
spec/spec_helper.rb:
  ap_load_workaround_extra: |
    "# Ugly hack, because there can only be one libdir
    `rsync -a #{Puppet[:modulepath]}/mount_providers/lib/ #{Puppet[:modulepath]}/augeasproviders_core/lib`"
